### ISSUE TITLE
Servislerimiz modülü üzerinde düzenleme

### ISSUE THREAD

**Issue by kdrcrm** [kadiruysal57/Laravel-basic-project#64]
servisler kısmında
açıklama kısmı boş geçilebilecek
bütün sitede zorunlu alanlar validation'lara bağlanacak
resim alanı zorunlu alan olmayacak
sıra alanı eklenecek (colum alan adı list_order olacak ben ekledim migrationlara ve modele)
resimler veritabanına eklerken str_replaceden geçmeli örn:
str_replace(env('APP_URL'),'',$request->language_icon_input)
silme butonu eklenmeli edit kısmına

**Comment by furkancilooglu** [comment]
Burada yazan her şey yapıldı. Sadece silmeden sonra data-table bulamadığından ilk aşamada boş sayfa gösteriyor onu çözemedim tekrar bakacağım. Fakat silme işlemi başarı ile gerçekleşiyor.
